### ISSUE TITLE
Filename replace - dash to underscore

### ISSUE THREAD

**Issue by CU-Sam** [justerest/multi-replace#2]
Hi. I just downloaded your vscode extention and it's just what I needed for my projects. But I saw that when I use a dash in the replace statement it is converted to underscore (when I want to rename multiple files).
Could it be possible to add an option to keep dashes ?

Example : If I replace "foo" by "test-ctrl" will be converted to "test_ctrl"

Thanks

**Comment by justerest** [comment]
Hi!
I have no idea how to resolve case with single word pattern ('test' -> 'smart-case-test').
It's impossible to use kebab-case in *.ts files. And some projects use another rules for file naming. It's will be grate to add configurable settings for vscode extantion with case identifications for common file extansions (and separate settings for path transformation). But it's long way and I can't promise to resolve it soon.

In last version (sorry, but my changelog is broken) I added transformation for Angular subjects:
If replace "foo service" by "bar baz service" on "foo.service.ts" will be converted to "bar-baz.service.ts". I hope it's feature helps.

**Comment by CU-Sam** [comment]
I understand that it'is not easy to do. I think the change you made in last version will help. Thanks for your reply !
